### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by suhan21** [hassancs91/ImageBackgroundRemover#4]
Traceback (most recent call last):
  File "/home/suhan/DLPro/Image-Background-Remover-Python-main/__init__.py", line 113, in <module>
    print(removeBg(imgPath))
  File "/home/suhan/DLPro/Image-Background-Remover-Python-main/__init__.py", line 82, in removeBg
    d1, d2, d3, d4, d5, d6, d7 = net(image)

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

Hi , I have install all the necessary packages and i use interpreter as conda. I Got the above error. I can't able to solve. Please, can you help me to solve this.Thanks in advance.

**Comment by hassancs91** [comment]
what type of images you are testing with?

**Comment by suhan21** [comment]
I have testing as the same cat image, even i also used python default interpreter / conda(base) interpreter i can't solve runtime error.
Here, i attached the screenshot.

![Screenshot from 2022-07-06 16-05-53](https://user-images.githubusercontent.com/85468635/177531758-39b8af7d-e930-4a96-bd0b-a7eb9e3815b8.png)

**Comment by suhan21** [comment]
hassan Please Can you help me to solve this issues

Thanks in advance

**Comment by Armando1206** [comment]
I have the same problem, can u help us?

**Comment by BhaumikThakkar** [comment]
> hassan Please Can you help me to solve this issues
> 
> Thanks in advance

Try on google colab

**Comment by njupt99lee** [comment]
> I have testing as the same cat image, even i also used python default interpreter / conda(base) interpreter i can't solve runtime error. Here, i attached the screenshot.
> 
> ![Screenshot from 2022-07-06 16-05-53](https://user-images.githubusercontent.com/85468635/177531758-39b8af7d-e930-4a96-bd0b-a7eb9e3815b8.png)

try this :  line 81     image = image.type(torch.FloatTensor)  ->     image = image.type(torch.cuda.FloatTensor)
