### ISSUE TITLE
File not found u2net.pth

### ISSUE THREAD

**Issue by chefbennyj1** [hassancs91/ImageBackgroundRemover#5]
Hi, I finally got this python project to  start loading models.
Realizing that python must be a 64bit version in order to install torch, and many other trial and error. :) 

However, now I'm getting a runtime error because I apparently don't have a model u2net.pth.

`Traceback (most recent call last):
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python38\Image-Background-Remover-Python-main\__init__.py", line 106, in <module>
    net.load_state_dict(torch.load(model_dir, map_location='cpu'))
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Benjamin\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Benjamin\\AppData\\Local\\Programs\\Python\\Python38\\Image-Background-Remover-Python-main\\saved_models\\u2net\\u2net.pth'`

How do I build this model?

Many thanks!

**Comment by chefbennyj1** [comment]
Okay, so after a while toying with this app (I'm a c# programmer... but a programmer non the less), I was finally able to get this to work.

1.  You have to get the u2net.pth file from their google drive here: 

https://drive.google.com/u/0/uc?id=1ao1ovG1Qtx4b7EoskHXmi2E9rp5CHLcZ&export=download

2. Make sure your images are not overly complicated or else you'll end up with something like this:

Image:
![Primary](https://user-images.githubusercontent.com/6015358/188328356-1f836e5f-661a-4ecc-a402-45acd5e39976.jpg)

Results:
![f6790563-8e36-4570-a25e-10ab9bd66e9b](https://user-images.githubusercontent.com/6015358/188328341-92dbddb0-1ca0-4bd9-a802-3788c619a1d6.png)

**Comment by ArthurSimoess** [comment]
Hello, @chefbennyj1 To be able to deploy the application do I need to upload the u2net.pth file to github? I saw that it is too big, and github doesn't accept it, the message appears: File saved_models/u2net/u2net.pth is 168.12 MB; this exceeds GitHub's file size limit of 100.00 MB.

**Comment by HiustonHo** [comment]
Hi can reshare the u2net.pth or how can we build this model?
